package it.portalECI.DTO;

import java.util.HashSet;
import java.util.Iterator;
import java.util.Set;

// default package
// Generated 15-feb-2017 9.30.19 by Hibernate Tools 3.4.0.CR1

/**
 * Utentedto generated by hbm2java
 */
public class UtenteDTO {

	private int id;
	private String user;
	private String passw;
	private String nominativo;
	private String nome;
	private String cognome;
	private String indirizzo;
	private String comune;
	private String cap;
	private String EMail;
	private String telefono;
	private CompanyDTO company;
	private String tipoutente;

	private Set<RuoloDTO> listaRuoli = new HashSet<RuoloDTO>(0);
	
	public UtenteDTO() {
	}


	public UtenteDTO(int id, String user, String passw, String nominativo,
			String nome, String cognome, String indirizzo, String comune,
			String cap, String EMail, String telefono, CompanyDTO _company,
			String tipoutente) {
		this.id = id;
		this.user = user;
		this.passw = passw;
		this.nominativo = nominativo;
		this.nome = nome;
		this.cognome = cognome;
		this.indirizzo = indirizzo;
		this.comune = comune;
		this.cap = cap;
		this.EMail = EMail;
		this.telefono = telefono;
		this.company = _company;
		this.tipoutente = tipoutente;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getUser() {
		return this.user;
	}

	public void setUser(String user) {
		this.user = user;
	}

	public String getPassw() {
		return this.passw;
	}

	public void setPassw(String passw) {
		this.passw = passw;
	}

	public String getNominativo() {
		return this.nominativo;
	}

	public void setNominativo(String nominativo) {
		this.nominativo = nominativo;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getCognome() {
		return this.cognome;
	}

	public void setCognome(String cognome) {
		this.cognome = cognome;
	}

	public String getIndirizzo() {
		return this.indirizzo;
	}

	public void setIndirizzo(String indirizzo) {
		this.indirizzo = indirizzo;
	}

	public String getComune() {
		return this.comune;
	}

	public void setComune(String comune) {
		this.comune = comune;
	}

	public String getCap() {
		return this.cap;
	}

	public void setCap(String cap) {
		this.cap = cap;
	}

	public String getEMail() {
		return this.EMail;
	}

	public void setEMail(String EMail) {
		this.EMail = EMail;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public String getTipoutente() {
		return this.tipoutente;
	}

	public void setTipoutente(String tipoutente) {
		this.tipoutente = tipoutente;
	}


	public Set<RuoloDTO> getListaRuoli() {
		return listaRuoli;
	}


	public void setListaRuoli(Set<RuoloDTO> listaRuoli) {
		this.listaRuoli = listaRuoli;
	}
	
	public boolean checkPermesso(String chiavePermesso)
	{
		 Iterator<RuoloDTO> iterator = listaRuoli.iterator(); 
	      
		   while (iterator.hasNext()){
			   
			RuoloDTO ruolo= (RuoloDTO) iterator.next(); 
			  
			
			Iterator<PermessoDTO> iteratorPermessi=(Iterator<PermessoDTO>) ruolo.getListaPermessi().iterator();
			
			while(iteratorPermessi.hasNext())
			{
				PermessoDTO permesso=iteratorPermessi.next();
				
				if(permesso.getChiave_permesso().equals(chiavePermesso))
				{
					return true;
				}
			}
		   
		   }
		   
		return false;
	}

	public boolean checkRuolo(String siglaRuolo)
	{
		 Iterator<RuoloDTO> iterator = listaRuoli.iterator(); 
	      
		   while (iterator.hasNext()){
			   
			RuoloDTO ruolo= (RuoloDTO) iterator.next(); 
			
			if(ruolo.getSigla().equals(siglaRuolo))
			{
				return true;
			}
		   }
		   
		return false;
	}


	public CompanyDTO getCompany() {
		return company;
	}


	public void setCompany(CompanyDTO company) {
		this.company = company;
	}
}
